server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        # 换成nginx的1111端口
        server-addr: 192.168.154.21:1111
      #        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"